##
## Makefile<3> for freewar in /u/ept2/skondr_m
## 
## Made by mael skondras
## Login   <skondr_m@epita.fr>
## 
## Started on  Wed May  5 16:52:02 2004 mael skondras
## Last update Thu May 13 15:38:50 2004 mael skondras
##

SRC_PATH	=	src
NAME 		=	AFirstChaos_`uname -s`

$(NAME)	:
		@cd $(SRC_PATH) && make

clean	:
		@cd $(SRC_PATH) && make clean

fclean	:
		@cd $(SRC_PATH) && make fclean

re	:
		@cd $(SRC_PATH) && make re
